name = "Bear Cub"
license = "MIT"
licenselink = "https://github.com/solomonarul/hugo-bearcub/blob/master/LICENSE"
description = "A fork of the Bearcub Hugo theme modified for my own personal use."
homepage = "https://github.com/solomonarul/hugo-bearcub"
demosite = "https://solomonarul.github.io"
[author]
    name = "Solomonarul"
    homepage = "https://solomonarul.github.io"
[original]
    name = "Caio Lente"
    homepage = "https://lente.dev"
    repo = "https://github.com/clente/hugo-bearcub"
[module]
  [module.hugoVersion]
    min = "0.90"
